### ISSUE TITLE
Have you get a best value of gamma and alpha?

### ISSUE THREAD

**Issue by cjt222** [jimitshah77/Focal-CTC-OMR#3]
In fact, i do not get better result when gamma =2 ,alpha=0.5 and gamma =0.5 ,alpha=0.25. Have you get a best result and which value do you choose?

**Comment by jimitshah77** [comment]
What I did was...
First set the value of Gamma, then use alpha as learning rate, to speedup.
Basically find the best alpha for a particular gamma value, then compare different gamma values.
